# -*- coding: utf-8 -*-
"""nm project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qY82U3-PykFuJKgCwBHVbh8Hz9ts8xW-
"""

import os
import openai
openai.api_key = os.getenv("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")
event_name = "College Coding Competition"
event_date = "April 15, 2024"
event_time = "10:00 AM"
event_location = "Lecture Hall 3"
event_speaker = "Professor Smith"
event_description = "A coding competition for all skill levels. Test your programming skills and win exciting prizes!"
registration_link = "https://forms.gle/collegecoding"
faqs = {
    "What is the event about?": event_description,
    "When is the event?": f"{event_date} at {event_time}",
    "Where is the event?": event_location,
    "Who is the speaker?": event_speaker,
    "Is registration required?": "Yes, you can register here: " + registration_link,
    "Can I participate if I'm a beginner?": "Absolutely! The competition is open to all skill levels."
}

def get_faq_answer(question):
  for key, answer in faqs.items():
    if question.lower().startswith(key.lower()):
      return answer
  return "I don't know, but I can try to answer a different question."

def send_message_to_chatgpt(message):
  response = openai.completions.create(
      engine="text-davinci-003",
      prompt=message,
      max_tokens=1024,
      n=1,
      stop=None,
      temperature=0.7,
  )
  return response.choices[0].text.strip()

def main():
  print(f"Welcome to the {event_name} chatbot!")
  while True:
    user_input = input("You: ").lower()
    if user_input == "quit":
      break
    answer = get_faq_answer(user_input)
    if answer != "I don't know":
      print(answer)
    else:
      chatgpt_response = send_message_to_chatgpt(user_input)
      print(f"ChatGPT: {chatgpt_response}")
if __name__ == "__main__":
  main()